/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardProductosIndexRouteImport } from './routes/_dashboard/productos/index'
import { Route as DashboardPedidosIndexRouteImport } from './routes/_dashboard/pedidos/index'
import { Route as DashboardCategoriasIndexRouteImport } from './routes/_dashboard/categorias/index'
import { Route as DashboardBundlesIndexRouteImport } from './routes/_dashboard/bundles/index'
import { Route as ApiUploadthingSplatRouteImport } from './routes/api.uploadthing.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as DashboardProductosNuevoRouteImport } from './routes/_dashboard/productos/nuevo'
import { Route as DashboardProductosIdRouteImport } from './routes/_dashboard/productos/$id'
import { Route as DashboardPedidosIdRouteImport } from './routes/_dashboard/pedidos/$id'
import { Route as DashboardBundlesNuevoRouteImport } from './routes/_dashboard/bundles/nuevo'
import { Route as DashboardBundlesIdRouteImport } from './routes/_dashboard/bundles/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardProductosIndexRoute = DashboardProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPedidosIndexRoute = DashboardPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriasIndexRoute =
  DashboardCategoriasIndexRouteImport.update({
    id: '/categorias/',
    path: '/categorias/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBundlesIndexRoute = DashboardBundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUploadthingSplatRoute = ApiUploadthingSplatRouteImport.update({
  id: '/api/uploadthing/$',
  path: '/api/uploadthing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductosNuevoRoute = DashboardProductosNuevoRouteImport.update({
  id: '/productos/nuevo',
  path: '/productos/nuevo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductosIdRoute = DashboardProductosIdRouteImport.update({
  id: '/productos/$id',
  path: '/productos/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPedidosIdRoute = DashboardPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBundlesNuevoRoute = DashboardBundlesNuevoRouteImport.update({
  id: '/bundles/nuevo',
  path: '/bundles/nuevo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBundlesIdRoute = DashboardBundlesIdRouteImport.update({
  id: '/bundles/$id',
  path: '/bundles/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof DashboardIndexRoute
  '/bundles/$id': typeof DashboardBundlesIdRoute
  '/bundles/nuevo': typeof DashboardBundlesNuevoRoute
  '/pedidos/$id': typeof DashboardPedidosIdRoute
  '/productos/$id': typeof DashboardProductosIdRoute
  '/productos/nuevo': typeof DashboardProductosNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/bundles': typeof DashboardBundlesIndexRoute
  '/categorias': typeof DashboardCategoriasIndexRoute
  '/pedidos': typeof DashboardPedidosIndexRoute
  '/productos': typeof DashboardProductosIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof DashboardIndexRoute
  '/bundles/$id': typeof DashboardBundlesIdRoute
  '/bundles/nuevo': typeof DashboardBundlesNuevoRoute
  '/pedidos/$id': typeof DashboardPedidosIdRoute
  '/productos/$id': typeof DashboardProductosIdRoute
  '/productos/nuevo': typeof DashboardProductosNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/bundles': typeof DashboardBundlesIndexRoute
  '/categorias': typeof DashboardCategoriasIndexRoute
  '/pedidos': typeof DashboardPedidosIndexRoute
  '/productos': typeof DashboardProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/api/$': typeof ApiSplatRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/bundles/$id': typeof DashboardBundlesIdRoute
  '/_dashboard/bundles/nuevo': typeof DashboardBundlesNuevoRoute
  '/_dashboard/pedidos/$id': typeof DashboardPedidosIdRoute
  '/_dashboard/productos/$id': typeof DashboardProductosIdRoute
  '/_dashboard/productos/nuevo': typeof DashboardProductosNuevoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/_dashboard/bundles/': typeof DashboardBundlesIndexRoute
  '/_dashboard/categorias/': typeof DashboardCategoriasIndexRoute
  '/_dashboard/pedidos/': typeof DashboardPedidosIndexRoute
  '/_dashboard/productos/': typeof DashboardProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/$'
    | '/'
    | '/bundles/$id'
    | '/bundles/nuevo'
    | '/pedidos/$id'
    | '/productos/$id'
    | '/productos/nuevo'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/bundles'
    | '/categorias'
    | '/pedidos'
    | '/productos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/api/$'
    | '/'
    | '/bundles/$id'
    | '/bundles/nuevo'
    | '/pedidos/$id'
    | '/productos/$id'
    | '/productos/nuevo'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/bundles'
    | '/categorias'
    | '/pedidos'
    | '/productos'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/api/$'
    | '/_dashboard/'
    | '/_dashboard/bundles/$id'
    | '/_dashboard/bundles/nuevo'
    | '/_dashboard/pedidos/$id'
    | '/_dashboard/productos/$id'
    | '/_dashboard/productos/nuevo'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/_dashboard/bundles/'
    | '/_dashboard/categorias/'
    | '/_dashboard/pedidos/'
    | '/_dashboard/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadthingSplatRoute: typeof ApiUploadthingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/productos/': {
      id: '/_dashboard/productos/'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof DashboardProductosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pedidos/': {
      id: '/_dashboard/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof DashboardPedidosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/categorias/': {
      id: '/_dashboard/categorias/'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof DashboardCategoriasIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bundles/': {
      id: '/_dashboard/bundles/'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof DashboardBundlesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/uploadthing/$': {
      id: '/api/uploadthing/$'
      path: '/api/uploadthing/$'
      fullPath: '/api/uploadthing/$'
      preLoaderRoute: typeof ApiUploadthingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/productos/nuevo': {
      id: '/_dashboard/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/productos/nuevo'
      preLoaderRoute: typeof DashboardProductosNuevoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/productos/$id': {
      id: '/_dashboard/productos/$id'
      path: '/productos/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof DashboardProductosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pedidos/$id': {
      id: '/_dashboard/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof DashboardPedidosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bundles/nuevo': {
      id: '/_dashboard/bundles/nuevo'
      path: '/bundles/nuevo'
      fullPath: '/bundles/nuevo'
      preLoaderRoute: typeof DashboardBundlesNuevoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bundles/$id': {
      id: '/_dashboard/bundles/$id'
      path: '/bundles/$id'
      fullPath: '/bundles/$id'
      preLoaderRoute: typeof DashboardBundlesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBundlesIdRoute: typeof DashboardBundlesIdRoute
  DashboardBundlesNuevoRoute: typeof DashboardBundlesNuevoRoute
  DashboardPedidosIdRoute: typeof DashboardPedidosIdRoute
  DashboardProductosIdRoute: typeof DashboardProductosIdRoute
  DashboardProductosNuevoRoute: typeof DashboardProductosNuevoRoute
  DashboardBundlesIndexRoute: typeof DashboardBundlesIndexRoute
  DashboardCategoriasIndexRoute: typeof DashboardCategoriasIndexRoute
  DashboardPedidosIndexRoute: typeof DashboardPedidosIndexRoute
  DashboardProductosIndexRoute: typeof DashboardProductosIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBundlesIdRoute: DashboardBundlesIdRoute,
  DashboardBundlesNuevoRoute: DashboardBundlesNuevoRoute,
  DashboardPedidosIdRoute: DashboardPedidosIdRoute,
  DashboardProductosIdRoute: DashboardProductosIdRoute,
  DashboardProductosNuevoRoute: DashboardProductosNuevoRoute,
  DashboardBundlesIndexRoute: DashboardBundlesIndexRoute,
  DashboardCategoriasIndexRoute: DashboardCategoriasIndexRoute,
  DashboardPedidosIndexRoute: DashboardPedidosIndexRoute,
  DashboardProductosIndexRoute: DashboardProductosIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadthingSplatRoute: ApiUploadthingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
