/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DashboardPerfilRouteImport } from './routes/_dashboard/perfil'
import { Route as DashboardConfiguracionRouteImport } from './routes/_dashboard/configuracion'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardResenasIndexRouteImport } from './routes/_dashboard/resenas/index'
import { Route as DashboardProductosIndexRouteImport } from './routes/_dashboard/productos/index'
import { Route as DashboardPedidosIndexRouteImport } from './routes/_dashboard/pedidos/index'
import { Route as DashboardPaginasIndexRouteImport } from './routes/_dashboard/paginas/index'
import { Route as DashboardMiCuentaIndexRouteImport } from './routes/_dashboard/mi-cuenta/index'
import { Route as DashboardInventarioIndexRouteImport } from './routes/_dashboard/inventario/index'
import { Route as DashboardCuponesIndexRouteImport } from './routes/_dashboard/cupones/index'
import { Route as DashboardConfiguracionIndexRouteImport } from './routes/_dashboard/configuracion/index'
import { Route as DashboardClientesIndexRouteImport } from './routes/_dashboard/clientes/index'
import { Route as DashboardCategoriasIndexRouteImport } from './routes/_dashboard/categorias/index'
import { Route as DashboardCarritosAbandonadosIndexRouteImport } from './routes/_dashboard/carritos-abandonados/index'
import { Route as DashboardBundlesIndexRouteImport } from './routes/_dashboard/bundles/index'
import { Route as ApiUploadthingSplatRouteImport } from './routes/api.uploadthing.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as DashboardResenasIdRouteImport } from './routes/_dashboard/resenas/$id'
import { Route as DashboardProductosNuevoRouteImport } from './routes/_dashboard/productos/nuevo'
import { Route as DashboardProductosIdRouteImport } from './routes/_dashboard/productos/$id'
import { Route as DashboardPedidosIdRouteImport } from './routes/_dashboard/pedidos/$id'
import { Route as DashboardPaginasNuevoRouteImport } from './routes/_dashboard/paginas/nuevo'
import { Route as DashboardPaginasIdRouteImport } from './routes/_dashboard/paginas/$id'
import { Route as DashboardMiCuentaPedidosRouteImport } from './routes/_dashboard/mi-cuenta/pedidos'
import { Route as DashboardCuponesNuevoRouteImport } from './routes/_dashboard/cupones/nuevo'
import { Route as DashboardCuponesIdRouteImport } from './routes/_dashboard/cupones/$id'
import { Route as DashboardConfiguracionSeoRouteImport } from './routes/_dashboard/configuracion/seo'
import { Route as DashboardConfiguracionRedesRouteImport } from './routes/_dashboard/configuracion/redes'
import { Route as DashboardConfiguracionNotificacionesRouteImport } from './routes/_dashboard/configuracion/notificaciones'
import { Route as DashboardConfiguracionGeneralRouteImport } from './routes/_dashboard/configuracion/general'
import { Route as DashboardConfiguracionEnvioRouteImport } from './routes/_dashboard/configuracion/envio'
import { Route as DashboardConfiguracionBrandingRouteImport } from './routes/_dashboard/configuracion/branding'
import { Route as DashboardClientesIdRouteImport } from './routes/_dashboard/clientes/$id'
import { Route as DashboardCarritosAbandonadosIdRouteImport } from './routes/_dashboard/carritos-abandonados/$id'
import { Route as DashboardBundlesNuevoRouteImport } from './routes/_dashboard/bundles/nuevo'
import { Route as DashboardBundlesIdRouteImport } from './routes/_dashboard/bundles/$id'
import { Route as DashboardProductosIdIndexRouteImport } from './routes/_dashboard/productos/$id/index'
import { Route as DashboardPedidosIdIndexRouteImport } from './routes/_dashboard/pedidos/$id/index'
import { Route as DashboardProductosIdVariantesRouteImport } from './routes/_dashboard/productos/$id/variantes'
import { Route as DashboardProductosIdSeoRouteImport } from './routes/_dashboard/productos/$id/seo'
import { Route as DashboardProductosIdPreciosRouteImport } from './routes/_dashboard/productos/$id/precios'
import { Route as DashboardProductosIdInventarioRouteImport } from './routes/_dashboard/productos/$id/inventario'
import { Route as DashboardProductosIdInfoRouteImport } from './routes/_dashboard/productos/$id/info'
import { Route as DashboardProductosIdImagenesRouteImport } from './routes/_dashboard/productos/$id/imagenes'
import { Route as DashboardPedidosIdResumenRouteImport } from './routes/_dashboard/pedidos/$id/resumen'
import { Route as DashboardPedidosIdProductosRouteImport } from './routes/_dashboard/pedidos/$id/productos'
import { Route as DashboardPedidosIdPagosRouteImport } from './routes/_dashboard/pedidos/$id/pagos'
import { Route as DashboardPedidosIdHistorialRouteImport } from './routes/_dashboard/pedidos/$id/historial'
import { Route as DashboardPedidosIdClienteRouteImport } from './routes/_dashboard/pedidos/$id/cliente'
import { Route as DashboardMiCuentaPedidosIdRouteImport } from './routes/_dashboard/mi-cuenta/pedidos.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracionRoute = DashboardConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardResenasIndexRoute = DashboardResenasIndexRouteImport.update({
  id: '/resenas/',
  path: '/resenas/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductosIndexRoute = DashboardProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPedidosIndexRoute = DashboardPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaginasIndexRoute = DashboardPaginasIndexRouteImport.update({
  id: '/paginas/',
  path: '/paginas/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMiCuentaIndexRoute = DashboardMiCuentaIndexRouteImport.update({
  id: '/mi-cuenta/',
  path: '/mi-cuenta/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventarioIndexRoute =
  DashboardInventarioIndexRouteImport.update({
    id: '/inventario/',
    path: '/inventario/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCuponesIndexRoute = DashboardCuponesIndexRouteImport.update({
  id: '/cupones/',
  path: '/cupones/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracionIndexRoute =
  DashboardConfiguracionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardConfiguracionRoute,
  } as any)
const DashboardClientesIndexRoute = DashboardClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriasIndexRoute =
  DashboardCategoriasIndexRouteImport.update({
    id: '/categorias/',
    path: '/categorias/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCarritosAbandonadosIndexRoute =
  DashboardCarritosAbandonadosIndexRouteImport.update({
    id: '/carritos-abandonados/',
    path: '/carritos-abandonados/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBundlesIndexRoute = DashboardBundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUploadthingSplatRoute = ApiUploadthingSplatRouteImport.update({
  id: '/api/uploadthing/$',
  path: '/api/uploadthing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResenasIdRoute = DashboardResenasIdRouteImport.update({
  id: '/resenas/$id',
  path: '/resenas/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductosNuevoRoute = DashboardProductosNuevoRouteImport.update({
  id: '/productos/nuevo',
  path: '/productos/nuevo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductosIdRoute = DashboardProductosIdRouteImport.update({
  id: '/productos/$id',
  path: '/productos/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPedidosIdRoute = DashboardPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaginasNuevoRoute = DashboardPaginasNuevoRouteImport.update({
  id: '/paginas/nuevo',
  path: '/paginas/nuevo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaginasIdRoute = DashboardPaginasIdRouteImport.update({
  id: '/paginas/$id',
  path: '/paginas/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMiCuentaPedidosRoute =
  DashboardMiCuentaPedidosRouteImport.update({
    id: '/mi-cuenta/pedidos',
    path: '/mi-cuenta/pedidos',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCuponesNuevoRoute = DashboardCuponesNuevoRouteImport.update({
  id: '/cupones/nuevo',
  path: '/cupones/nuevo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCuponesIdRoute = DashboardCuponesIdRouteImport.update({
  id: '/cupones/$id',
  path: '/cupones/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracionSeoRoute =
  DashboardConfiguracionSeoRouteImport.update({
    id: '/seo',
    path: '/seo',
    getParentRoute: () => DashboardConfiguracionRoute,
  } as any)
const DashboardConfiguracionRedesRoute =
  DashboardConfiguracionRedesRouteImport.update({
    id: '/redes',
    path: '/redes',
    getParentRoute: () => DashboardConfiguracionRoute,
  } as any)
const DashboardConfiguracionNotificacionesRoute =
  DashboardConfiguracionNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => DashboardConfiguracionRoute,
  } as any)
const DashboardConfiguracionGeneralRoute =
  DashboardConfiguracionGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardConfiguracionRoute,
  } as any)
const DashboardConfiguracionEnvioRoute =
  DashboardConfiguracionEnvioRouteImport.update({
    id: '/envio',
    path: '/envio',
    getParentRoute: () => DashboardConfiguracionRoute,
  } as any)
const DashboardConfiguracionBrandingRoute =
  DashboardConfiguracionBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => DashboardConfiguracionRoute,
  } as any)
const DashboardClientesIdRoute = DashboardClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCarritosAbandonadosIdRoute =
  DashboardCarritosAbandonadosIdRouteImport.update({
    id: '/carritos-abandonados/$id',
    path: '/carritos-abandonados/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBundlesNuevoRoute = DashboardBundlesNuevoRouteImport.update({
  id: '/bundles/nuevo',
  path: '/bundles/nuevo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBundlesIdRoute = DashboardBundlesIdRouteImport.update({
  id: '/bundles/$id',
  path: '/bundles/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductosIdIndexRoute =
  DashboardProductosIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProductosIdRoute,
  } as any)
const DashboardPedidosIdIndexRoute = DashboardPedidosIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPedidosIdRoute,
} as any)
const DashboardProductosIdVariantesRoute =
  DashboardProductosIdVariantesRouteImport.update({
    id: '/variantes',
    path: '/variantes',
    getParentRoute: () => DashboardProductosIdRoute,
  } as any)
const DashboardProductosIdSeoRoute = DashboardProductosIdSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => DashboardProductosIdRoute,
} as any)
const DashboardProductosIdPreciosRoute =
  DashboardProductosIdPreciosRouteImport.update({
    id: '/precios',
    path: '/precios',
    getParentRoute: () => DashboardProductosIdRoute,
  } as any)
const DashboardProductosIdInventarioRoute =
  DashboardProductosIdInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => DashboardProductosIdRoute,
  } as any)
const DashboardProductosIdInfoRoute =
  DashboardProductosIdInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => DashboardProductosIdRoute,
  } as any)
const DashboardProductosIdImagenesRoute =
  DashboardProductosIdImagenesRouteImport.update({
    id: '/imagenes',
    path: '/imagenes',
    getParentRoute: () => DashboardProductosIdRoute,
  } as any)
const DashboardPedidosIdResumenRoute =
  DashboardPedidosIdResumenRouteImport.update({
    id: '/resumen',
    path: '/resumen',
    getParentRoute: () => DashboardPedidosIdRoute,
  } as any)
const DashboardPedidosIdProductosRoute =
  DashboardPedidosIdProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => DashboardPedidosIdRoute,
  } as any)
const DashboardPedidosIdPagosRoute = DashboardPedidosIdPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => DashboardPedidosIdRoute,
} as any)
const DashboardPedidosIdHistorialRoute =
  DashboardPedidosIdHistorialRouteImport.update({
    id: '/historial',
    path: '/historial',
    getParentRoute: () => DashboardPedidosIdRoute,
  } as any)
const DashboardPedidosIdClienteRoute =
  DashboardPedidosIdClienteRouteImport.update({
    id: '/cliente',
    path: '/cliente',
    getParentRoute: () => DashboardPedidosIdRoute,
  } as any)
const DashboardMiCuentaPedidosIdRoute =
  DashboardMiCuentaPedidosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardMiCuentaPedidosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/configuracion': typeof DashboardConfiguracionRouteWithChildren
  '/perfil': typeof DashboardPerfilRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof DashboardIndexRoute
  '/bundles/$id': typeof DashboardBundlesIdRoute
  '/bundles/nuevo': typeof DashboardBundlesNuevoRoute
  '/carritos-abandonados/$id': typeof DashboardCarritosAbandonadosIdRoute
  '/clientes/$id': typeof DashboardClientesIdRoute
  '/configuracion/branding': typeof DashboardConfiguracionBrandingRoute
  '/configuracion/envio': typeof DashboardConfiguracionEnvioRoute
  '/configuracion/general': typeof DashboardConfiguracionGeneralRoute
  '/configuracion/notificaciones': typeof DashboardConfiguracionNotificacionesRoute
  '/configuracion/redes': typeof DashboardConfiguracionRedesRoute
  '/configuracion/seo': typeof DashboardConfiguracionSeoRoute
  '/cupones/$id': typeof DashboardCuponesIdRoute
  '/cupones/nuevo': typeof DashboardCuponesNuevoRoute
  '/mi-cuenta/pedidos': typeof DashboardMiCuentaPedidosRouteWithChildren
  '/paginas/$id': typeof DashboardPaginasIdRoute
  '/paginas/nuevo': typeof DashboardPaginasNuevoRoute
  '/pedidos/$id': typeof DashboardPedidosIdRouteWithChildren
  '/productos/$id': typeof DashboardProductosIdRouteWithChildren
  '/productos/nuevo': typeof DashboardProductosNuevoRoute
  '/resenas/$id': typeof DashboardResenasIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/bundles': typeof DashboardBundlesIndexRoute
  '/carritos-abandonados': typeof DashboardCarritosAbandonadosIndexRoute
  '/categorias': typeof DashboardCategoriasIndexRoute
  '/clientes': typeof DashboardClientesIndexRoute
  '/configuracion/': typeof DashboardConfiguracionIndexRoute
  '/cupones': typeof DashboardCuponesIndexRoute
  '/inventario': typeof DashboardInventarioIndexRoute
  '/mi-cuenta': typeof DashboardMiCuentaIndexRoute
  '/paginas': typeof DashboardPaginasIndexRoute
  '/pedidos': typeof DashboardPedidosIndexRoute
  '/productos': typeof DashboardProductosIndexRoute
  '/resenas': typeof DashboardResenasIndexRoute
  '/mi-cuenta/pedidos/$id': typeof DashboardMiCuentaPedidosIdRoute
  '/pedidos/$id/cliente': typeof DashboardPedidosIdClienteRoute
  '/pedidos/$id/historial': typeof DashboardPedidosIdHistorialRoute
  '/pedidos/$id/pagos': typeof DashboardPedidosIdPagosRoute
  '/pedidos/$id/productos': typeof DashboardPedidosIdProductosRoute
  '/pedidos/$id/resumen': typeof DashboardPedidosIdResumenRoute
  '/productos/$id/imagenes': typeof DashboardProductosIdImagenesRoute
  '/productos/$id/info': typeof DashboardProductosIdInfoRoute
  '/productos/$id/inventario': typeof DashboardProductosIdInventarioRoute
  '/productos/$id/precios': typeof DashboardProductosIdPreciosRoute
  '/productos/$id/seo': typeof DashboardProductosIdSeoRoute
  '/productos/$id/variantes': typeof DashboardProductosIdVariantesRoute
  '/pedidos/$id/': typeof DashboardPedidosIdIndexRoute
  '/productos/$id/': typeof DashboardProductosIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/perfil': typeof DashboardPerfilRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof DashboardIndexRoute
  '/bundles/$id': typeof DashboardBundlesIdRoute
  '/bundles/nuevo': typeof DashboardBundlesNuevoRoute
  '/carritos-abandonados/$id': typeof DashboardCarritosAbandonadosIdRoute
  '/clientes/$id': typeof DashboardClientesIdRoute
  '/configuracion/branding': typeof DashboardConfiguracionBrandingRoute
  '/configuracion/envio': typeof DashboardConfiguracionEnvioRoute
  '/configuracion/general': typeof DashboardConfiguracionGeneralRoute
  '/configuracion/notificaciones': typeof DashboardConfiguracionNotificacionesRoute
  '/configuracion/redes': typeof DashboardConfiguracionRedesRoute
  '/configuracion/seo': typeof DashboardConfiguracionSeoRoute
  '/cupones/$id': typeof DashboardCuponesIdRoute
  '/cupones/nuevo': typeof DashboardCuponesNuevoRoute
  '/mi-cuenta/pedidos': typeof DashboardMiCuentaPedidosRouteWithChildren
  '/paginas/$id': typeof DashboardPaginasIdRoute
  '/paginas/nuevo': typeof DashboardPaginasNuevoRoute
  '/productos/nuevo': typeof DashboardProductosNuevoRoute
  '/resenas/$id': typeof DashboardResenasIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/bundles': typeof DashboardBundlesIndexRoute
  '/carritos-abandonados': typeof DashboardCarritosAbandonadosIndexRoute
  '/categorias': typeof DashboardCategoriasIndexRoute
  '/clientes': typeof DashboardClientesIndexRoute
  '/configuracion': typeof DashboardConfiguracionIndexRoute
  '/cupones': typeof DashboardCuponesIndexRoute
  '/inventario': typeof DashboardInventarioIndexRoute
  '/mi-cuenta': typeof DashboardMiCuentaIndexRoute
  '/paginas': typeof DashboardPaginasIndexRoute
  '/pedidos': typeof DashboardPedidosIndexRoute
  '/productos': typeof DashboardProductosIndexRoute
  '/resenas': typeof DashboardResenasIndexRoute
  '/mi-cuenta/pedidos/$id': typeof DashboardMiCuentaPedidosIdRoute
  '/pedidos/$id/cliente': typeof DashboardPedidosIdClienteRoute
  '/pedidos/$id/historial': typeof DashboardPedidosIdHistorialRoute
  '/pedidos/$id/pagos': typeof DashboardPedidosIdPagosRoute
  '/pedidos/$id/productos': typeof DashboardPedidosIdProductosRoute
  '/pedidos/$id/resumen': typeof DashboardPedidosIdResumenRoute
  '/productos/$id/imagenes': typeof DashboardProductosIdImagenesRoute
  '/productos/$id/info': typeof DashboardProductosIdInfoRoute
  '/productos/$id/inventario': typeof DashboardProductosIdInventarioRoute
  '/productos/$id/precios': typeof DashboardProductosIdPreciosRoute
  '/productos/$id/seo': typeof DashboardProductosIdSeoRoute
  '/productos/$id/variantes': typeof DashboardProductosIdVariantesRoute
  '/pedidos/$id': typeof DashboardPedidosIdIndexRoute
  '/productos/$id': typeof DashboardProductosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_dashboard/configuracion': typeof DashboardConfiguracionRouteWithChildren
  '/_dashboard/perfil': typeof DashboardPerfilRoute
  '/api/$': typeof ApiSplatRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/bundles/$id': typeof DashboardBundlesIdRoute
  '/_dashboard/bundles/nuevo': typeof DashboardBundlesNuevoRoute
  '/_dashboard/carritos-abandonados/$id': typeof DashboardCarritosAbandonadosIdRoute
  '/_dashboard/clientes/$id': typeof DashboardClientesIdRoute
  '/_dashboard/configuracion/branding': typeof DashboardConfiguracionBrandingRoute
  '/_dashboard/configuracion/envio': typeof DashboardConfiguracionEnvioRoute
  '/_dashboard/configuracion/general': typeof DashboardConfiguracionGeneralRoute
  '/_dashboard/configuracion/notificaciones': typeof DashboardConfiguracionNotificacionesRoute
  '/_dashboard/configuracion/redes': typeof DashboardConfiguracionRedesRoute
  '/_dashboard/configuracion/seo': typeof DashboardConfiguracionSeoRoute
  '/_dashboard/cupones/$id': typeof DashboardCuponesIdRoute
  '/_dashboard/cupones/nuevo': typeof DashboardCuponesNuevoRoute
  '/_dashboard/mi-cuenta/pedidos': typeof DashboardMiCuentaPedidosRouteWithChildren
  '/_dashboard/paginas/$id': typeof DashboardPaginasIdRoute
  '/_dashboard/paginas/nuevo': typeof DashboardPaginasNuevoRoute
  '/_dashboard/pedidos/$id': typeof DashboardPedidosIdRouteWithChildren
  '/_dashboard/productos/$id': typeof DashboardProductosIdRouteWithChildren
  '/_dashboard/productos/nuevo': typeof DashboardProductosNuevoRoute
  '/_dashboard/resenas/$id': typeof DashboardResenasIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/uploadthing/$': typeof ApiUploadthingSplatRoute
  '/_dashboard/bundles/': typeof DashboardBundlesIndexRoute
  '/_dashboard/carritos-abandonados/': typeof DashboardCarritosAbandonadosIndexRoute
  '/_dashboard/categorias/': typeof DashboardCategoriasIndexRoute
  '/_dashboard/clientes/': typeof DashboardClientesIndexRoute
  '/_dashboard/configuracion/': typeof DashboardConfiguracionIndexRoute
  '/_dashboard/cupones/': typeof DashboardCuponesIndexRoute
  '/_dashboard/inventario/': typeof DashboardInventarioIndexRoute
  '/_dashboard/mi-cuenta/': typeof DashboardMiCuentaIndexRoute
  '/_dashboard/paginas/': typeof DashboardPaginasIndexRoute
  '/_dashboard/pedidos/': typeof DashboardPedidosIndexRoute
  '/_dashboard/productos/': typeof DashboardProductosIndexRoute
  '/_dashboard/resenas/': typeof DashboardResenasIndexRoute
  '/_dashboard/mi-cuenta/pedidos/$id': typeof DashboardMiCuentaPedidosIdRoute
  '/_dashboard/pedidos/$id/cliente': typeof DashboardPedidosIdClienteRoute
  '/_dashboard/pedidos/$id/historial': typeof DashboardPedidosIdHistorialRoute
  '/_dashboard/pedidos/$id/pagos': typeof DashboardPedidosIdPagosRoute
  '/_dashboard/pedidos/$id/productos': typeof DashboardPedidosIdProductosRoute
  '/_dashboard/pedidos/$id/resumen': typeof DashboardPedidosIdResumenRoute
  '/_dashboard/productos/$id/imagenes': typeof DashboardProductosIdImagenesRoute
  '/_dashboard/productos/$id/info': typeof DashboardProductosIdInfoRoute
  '/_dashboard/productos/$id/inventario': typeof DashboardProductosIdInventarioRoute
  '/_dashboard/productos/$id/precios': typeof DashboardProductosIdPreciosRoute
  '/_dashboard/productos/$id/seo': typeof DashboardProductosIdSeoRoute
  '/_dashboard/productos/$id/variantes': typeof DashboardProductosIdVariantesRoute
  '/_dashboard/pedidos/$id/': typeof DashboardPedidosIdIndexRoute
  '/_dashboard/productos/$id/': typeof DashboardProductosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/configuracion'
    | '/perfil'
    | '/api/$'
    | '/'
    | '/bundles/$id'
    | '/bundles/nuevo'
    | '/carritos-abandonados/$id'
    | '/clientes/$id'
    | '/configuracion/branding'
    | '/configuracion/envio'
    | '/configuracion/general'
    | '/configuracion/notificaciones'
    | '/configuracion/redes'
    | '/configuracion/seo'
    | '/cupones/$id'
    | '/cupones/nuevo'
    | '/mi-cuenta/pedidos'
    | '/paginas/$id'
    | '/paginas/nuevo'
    | '/pedidos/$id'
    | '/productos/$id'
    | '/productos/nuevo'
    | '/resenas/$id'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/bundles'
    | '/carritos-abandonados'
    | '/categorias'
    | '/clientes'
    | '/configuracion/'
    | '/cupones'
    | '/inventario'
    | '/mi-cuenta'
    | '/paginas'
    | '/pedidos'
    | '/productos'
    | '/resenas'
    | '/mi-cuenta/pedidos/$id'
    | '/pedidos/$id/cliente'
    | '/pedidos/$id/historial'
    | '/pedidos/$id/pagos'
    | '/pedidos/$id/productos'
    | '/pedidos/$id/resumen'
    | '/productos/$id/imagenes'
    | '/productos/$id/info'
    | '/productos/$id/inventario'
    | '/productos/$id/precios'
    | '/productos/$id/seo'
    | '/productos/$id/variantes'
    | '/pedidos/$id/'
    | '/productos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/perfil'
    | '/api/$'
    | '/'
    | '/bundles/$id'
    | '/bundles/nuevo'
    | '/carritos-abandonados/$id'
    | '/clientes/$id'
    | '/configuracion/branding'
    | '/configuracion/envio'
    | '/configuracion/general'
    | '/configuracion/notificaciones'
    | '/configuracion/redes'
    | '/configuracion/seo'
    | '/cupones/$id'
    | '/cupones/nuevo'
    | '/mi-cuenta/pedidos'
    | '/paginas/$id'
    | '/paginas/nuevo'
    | '/productos/nuevo'
    | '/resenas/$id'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/bundles'
    | '/carritos-abandonados'
    | '/categorias'
    | '/clientes'
    | '/configuracion'
    | '/cupones'
    | '/inventario'
    | '/mi-cuenta'
    | '/paginas'
    | '/pedidos'
    | '/productos'
    | '/resenas'
    | '/mi-cuenta/pedidos/$id'
    | '/pedidos/$id/cliente'
    | '/pedidos/$id/historial'
    | '/pedidos/$id/pagos'
    | '/pedidos/$id/productos'
    | '/pedidos/$id/resumen'
    | '/productos/$id/imagenes'
    | '/productos/$id/info'
    | '/productos/$id/inventario'
    | '/productos/$id/precios'
    | '/productos/$id/seo'
    | '/productos/$id/variantes'
    | '/pedidos/$id'
    | '/productos/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_dashboard/configuracion'
    | '/_dashboard/perfil'
    | '/api/$'
    | '/_dashboard/'
    | '/_dashboard/bundles/$id'
    | '/_dashboard/bundles/nuevo'
    | '/_dashboard/carritos-abandonados/$id'
    | '/_dashboard/clientes/$id'
    | '/_dashboard/configuracion/branding'
    | '/_dashboard/configuracion/envio'
    | '/_dashboard/configuracion/general'
    | '/_dashboard/configuracion/notificaciones'
    | '/_dashboard/configuracion/redes'
    | '/_dashboard/configuracion/seo'
    | '/_dashboard/cupones/$id'
    | '/_dashboard/cupones/nuevo'
    | '/_dashboard/mi-cuenta/pedidos'
    | '/_dashboard/paginas/$id'
    | '/_dashboard/paginas/nuevo'
    | '/_dashboard/pedidos/$id'
    | '/_dashboard/productos/$id'
    | '/_dashboard/productos/nuevo'
    | '/_dashboard/resenas/$id'
    | '/api/auth/$'
    | '/api/uploadthing/$'
    | '/_dashboard/bundles/'
    | '/_dashboard/carritos-abandonados/'
    | '/_dashboard/categorias/'
    | '/_dashboard/clientes/'
    | '/_dashboard/configuracion/'
    | '/_dashboard/cupones/'
    | '/_dashboard/inventario/'
    | '/_dashboard/mi-cuenta/'
    | '/_dashboard/paginas/'
    | '/_dashboard/pedidos/'
    | '/_dashboard/productos/'
    | '/_dashboard/resenas/'
    | '/_dashboard/mi-cuenta/pedidos/$id'
    | '/_dashboard/pedidos/$id/cliente'
    | '/_dashboard/pedidos/$id/historial'
    | '/_dashboard/pedidos/$id/pagos'
    | '/_dashboard/pedidos/$id/productos'
    | '/_dashboard/pedidos/$id/resumen'
    | '/_dashboard/productos/$id/imagenes'
    | '/_dashboard/productos/$id/info'
    | '/_dashboard/productos/$id/inventario'
    | '/_dashboard/productos/$id/precios'
    | '/_dashboard/productos/$id/seo'
    | '/_dashboard/productos/$id/variantes'
    | '/_dashboard/pedidos/$id/'
    | '/_dashboard/productos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadthingSplatRoute: typeof ApiUploadthingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/perfil': {
      id: '/_dashboard/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/configuracion': {
      id: '/_dashboard/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof DashboardConfiguracionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/resenas/': {
      id: '/_dashboard/resenas/'
      path: '/resenas'
      fullPath: '/resenas'
      preLoaderRoute: typeof DashboardResenasIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/productos/': {
      id: '/_dashboard/productos/'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof DashboardProductosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pedidos/': {
      id: '/_dashboard/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof DashboardPedidosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/paginas/': {
      id: '/_dashboard/paginas/'
      path: '/paginas'
      fullPath: '/paginas'
      preLoaderRoute: typeof DashboardPaginasIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mi-cuenta/': {
      id: '/_dashboard/mi-cuenta/'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof DashboardMiCuentaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inventario/': {
      id: '/_dashboard/inventario/'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof DashboardInventarioIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cupones/': {
      id: '/_dashboard/cupones/'
      path: '/cupones'
      fullPath: '/cupones'
      preLoaderRoute: typeof DashboardCuponesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/configuracion/': {
      id: '/_dashboard/configuracion/'
      path: '/'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof DashboardConfiguracionIndexRouteImport
      parentRoute: typeof DashboardConfiguracionRoute
    }
    '/_dashboard/clientes/': {
      id: '/_dashboard/clientes/'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof DashboardClientesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/categorias/': {
      id: '/_dashboard/categorias/'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof DashboardCategoriasIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/carritos-abandonados/': {
      id: '/_dashboard/carritos-abandonados/'
      path: '/carritos-abandonados'
      fullPath: '/carritos-abandonados'
      preLoaderRoute: typeof DashboardCarritosAbandonadosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bundles/': {
      id: '/_dashboard/bundles/'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof DashboardBundlesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/uploadthing/$': {
      id: '/api/uploadthing/$'
      path: '/api/uploadthing/$'
      fullPath: '/api/uploadthing/$'
      preLoaderRoute: typeof ApiUploadthingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/resenas/$id': {
      id: '/_dashboard/resenas/$id'
      path: '/resenas/$id'
      fullPath: '/resenas/$id'
      preLoaderRoute: typeof DashboardResenasIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/productos/nuevo': {
      id: '/_dashboard/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/productos/nuevo'
      preLoaderRoute: typeof DashboardProductosNuevoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/productos/$id': {
      id: '/_dashboard/productos/$id'
      path: '/productos/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof DashboardProductosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pedidos/$id': {
      id: '/_dashboard/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof DashboardPedidosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/paginas/nuevo': {
      id: '/_dashboard/paginas/nuevo'
      path: '/paginas/nuevo'
      fullPath: '/paginas/nuevo'
      preLoaderRoute: typeof DashboardPaginasNuevoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/paginas/$id': {
      id: '/_dashboard/paginas/$id'
      path: '/paginas/$id'
      fullPath: '/paginas/$id'
      preLoaderRoute: typeof DashboardPaginasIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mi-cuenta/pedidos': {
      id: '/_dashboard/mi-cuenta/pedidos'
      path: '/mi-cuenta/pedidos'
      fullPath: '/mi-cuenta/pedidos'
      preLoaderRoute: typeof DashboardMiCuentaPedidosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cupones/nuevo': {
      id: '/_dashboard/cupones/nuevo'
      path: '/cupones/nuevo'
      fullPath: '/cupones/nuevo'
      preLoaderRoute: typeof DashboardCuponesNuevoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cupones/$id': {
      id: '/_dashboard/cupones/$id'
      path: '/cupones/$id'
      fullPath: '/cupones/$id'
      preLoaderRoute: typeof DashboardCuponesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/configuracion/seo': {
      id: '/_dashboard/configuracion/seo'
      path: '/seo'
      fullPath: '/configuracion/seo'
      preLoaderRoute: typeof DashboardConfiguracionSeoRouteImport
      parentRoute: typeof DashboardConfiguracionRoute
    }
    '/_dashboard/configuracion/redes': {
      id: '/_dashboard/configuracion/redes'
      path: '/redes'
      fullPath: '/configuracion/redes'
      preLoaderRoute: typeof DashboardConfiguracionRedesRouteImport
      parentRoute: typeof DashboardConfiguracionRoute
    }
    '/_dashboard/configuracion/notificaciones': {
      id: '/_dashboard/configuracion/notificaciones'
      path: '/notificaciones'
      fullPath: '/configuracion/notificaciones'
      preLoaderRoute: typeof DashboardConfiguracionNotificacionesRouteImport
      parentRoute: typeof DashboardConfiguracionRoute
    }
    '/_dashboard/configuracion/general': {
      id: '/_dashboard/configuracion/general'
      path: '/general'
      fullPath: '/configuracion/general'
      preLoaderRoute: typeof DashboardConfiguracionGeneralRouteImport
      parentRoute: typeof DashboardConfiguracionRoute
    }
    '/_dashboard/configuracion/envio': {
      id: '/_dashboard/configuracion/envio'
      path: '/envio'
      fullPath: '/configuracion/envio'
      preLoaderRoute: typeof DashboardConfiguracionEnvioRouteImport
      parentRoute: typeof DashboardConfiguracionRoute
    }
    '/_dashboard/configuracion/branding': {
      id: '/_dashboard/configuracion/branding'
      path: '/branding'
      fullPath: '/configuracion/branding'
      preLoaderRoute: typeof DashboardConfiguracionBrandingRouteImport
      parentRoute: typeof DashboardConfiguracionRoute
    }
    '/_dashboard/clientes/$id': {
      id: '/_dashboard/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof DashboardClientesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/carritos-abandonados/$id': {
      id: '/_dashboard/carritos-abandonados/$id'
      path: '/carritos-abandonados/$id'
      fullPath: '/carritos-abandonados/$id'
      preLoaderRoute: typeof DashboardCarritosAbandonadosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bundles/nuevo': {
      id: '/_dashboard/bundles/nuevo'
      path: '/bundles/nuevo'
      fullPath: '/bundles/nuevo'
      preLoaderRoute: typeof DashboardBundlesNuevoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bundles/$id': {
      id: '/_dashboard/bundles/$id'
      path: '/bundles/$id'
      fullPath: '/bundles/$id'
      preLoaderRoute: typeof DashboardBundlesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/productos/$id/': {
      id: '/_dashboard/productos/$id/'
      path: '/'
      fullPath: '/productos/$id/'
      preLoaderRoute: typeof DashboardProductosIdIndexRouteImport
      parentRoute: typeof DashboardProductosIdRoute
    }
    '/_dashboard/pedidos/$id/': {
      id: '/_dashboard/pedidos/$id/'
      path: '/'
      fullPath: '/pedidos/$id/'
      preLoaderRoute: typeof DashboardPedidosIdIndexRouteImport
      parentRoute: typeof DashboardPedidosIdRoute
    }
    '/_dashboard/productos/$id/variantes': {
      id: '/_dashboard/productos/$id/variantes'
      path: '/variantes'
      fullPath: '/productos/$id/variantes'
      preLoaderRoute: typeof DashboardProductosIdVariantesRouteImport
      parentRoute: typeof DashboardProductosIdRoute
    }
    '/_dashboard/productos/$id/seo': {
      id: '/_dashboard/productos/$id/seo'
      path: '/seo'
      fullPath: '/productos/$id/seo'
      preLoaderRoute: typeof DashboardProductosIdSeoRouteImport
      parentRoute: typeof DashboardProductosIdRoute
    }
    '/_dashboard/productos/$id/precios': {
      id: '/_dashboard/productos/$id/precios'
      path: '/precios'
      fullPath: '/productos/$id/precios'
      preLoaderRoute: typeof DashboardProductosIdPreciosRouteImport
      parentRoute: typeof DashboardProductosIdRoute
    }
    '/_dashboard/productos/$id/inventario': {
      id: '/_dashboard/productos/$id/inventario'
      path: '/inventario'
      fullPath: '/productos/$id/inventario'
      preLoaderRoute: typeof DashboardProductosIdInventarioRouteImport
      parentRoute: typeof DashboardProductosIdRoute
    }
    '/_dashboard/productos/$id/info': {
      id: '/_dashboard/productos/$id/info'
      path: '/info'
      fullPath: '/productos/$id/info'
      preLoaderRoute: typeof DashboardProductosIdInfoRouteImport
      parentRoute: typeof DashboardProductosIdRoute
    }
    '/_dashboard/productos/$id/imagenes': {
      id: '/_dashboard/productos/$id/imagenes'
      path: '/imagenes'
      fullPath: '/productos/$id/imagenes'
      preLoaderRoute: typeof DashboardProductosIdImagenesRouteImport
      parentRoute: typeof DashboardProductosIdRoute
    }
    '/_dashboard/pedidos/$id/resumen': {
      id: '/_dashboard/pedidos/$id/resumen'
      path: '/resumen'
      fullPath: '/pedidos/$id/resumen'
      preLoaderRoute: typeof DashboardPedidosIdResumenRouteImport
      parentRoute: typeof DashboardPedidosIdRoute
    }
    '/_dashboard/pedidos/$id/productos': {
      id: '/_dashboard/pedidos/$id/productos'
      path: '/productos'
      fullPath: '/pedidos/$id/productos'
      preLoaderRoute: typeof DashboardPedidosIdProductosRouteImport
      parentRoute: typeof DashboardPedidosIdRoute
    }
    '/_dashboard/pedidos/$id/pagos': {
      id: '/_dashboard/pedidos/$id/pagos'
      path: '/pagos'
      fullPath: '/pedidos/$id/pagos'
      preLoaderRoute: typeof DashboardPedidosIdPagosRouteImport
      parentRoute: typeof DashboardPedidosIdRoute
    }
    '/_dashboard/pedidos/$id/historial': {
      id: '/_dashboard/pedidos/$id/historial'
      path: '/historial'
      fullPath: '/pedidos/$id/historial'
      preLoaderRoute: typeof DashboardPedidosIdHistorialRouteImport
      parentRoute: typeof DashboardPedidosIdRoute
    }
    '/_dashboard/pedidos/$id/cliente': {
      id: '/_dashboard/pedidos/$id/cliente'
      path: '/cliente'
      fullPath: '/pedidos/$id/cliente'
      preLoaderRoute: typeof DashboardPedidosIdClienteRouteImport
      parentRoute: typeof DashboardPedidosIdRoute
    }
    '/_dashboard/mi-cuenta/pedidos/$id': {
      id: '/_dashboard/mi-cuenta/pedidos/$id'
      path: '/$id'
      fullPath: '/mi-cuenta/pedidos/$id'
      preLoaderRoute: typeof DashboardMiCuentaPedidosIdRouteImport
      parentRoute: typeof DashboardMiCuentaPedidosRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardConfiguracionRouteChildren {
  DashboardConfiguracionBrandingRoute: typeof DashboardConfiguracionBrandingRoute
  DashboardConfiguracionEnvioRoute: typeof DashboardConfiguracionEnvioRoute
  DashboardConfiguracionGeneralRoute: typeof DashboardConfiguracionGeneralRoute
  DashboardConfiguracionNotificacionesRoute: typeof DashboardConfiguracionNotificacionesRoute
  DashboardConfiguracionRedesRoute: typeof DashboardConfiguracionRedesRoute
  DashboardConfiguracionSeoRoute: typeof DashboardConfiguracionSeoRoute
  DashboardConfiguracionIndexRoute: typeof DashboardConfiguracionIndexRoute
}

const DashboardConfiguracionRouteChildren: DashboardConfiguracionRouteChildren =
  {
    DashboardConfiguracionBrandingRoute: DashboardConfiguracionBrandingRoute,
    DashboardConfiguracionEnvioRoute: DashboardConfiguracionEnvioRoute,
    DashboardConfiguracionGeneralRoute: DashboardConfiguracionGeneralRoute,
    DashboardConfiguracionNotificacionesRoute:
      DashboardConfiguracionNotificacionesRoute,
    DashboardConfiguracionRedesRoute: DashboardConfiguracionRedesRoute,
    DashboardConfiguracionSeoRoute: DashboardConfiguracionSeoRoute,
    DashboardConfiguracionIndexRoute: DashboardConfiguracionIndexRoute,
  }

const DashboardConfiguracionRouteWithChildren =
  DashboardConfiguracionRoute._addFileChildren(
    DashboardConfiguracionRouteChildren,
  )

interface DashboardMiCuentaPedidosRouteChildren {
  DashboardMiCuentaPedidosIdRoute: typeof DashboardMiCuentaPedidosIdRoute
}

const DashboardMiCuentaPedidosRouteChildren: DashboardMiCuentaPedidosRouteChildren =
  {
    DashboardMiCuentaPedidosIdRoute: DashboardMiCuentaPedidosIdRoute,
  }

const DashboardMiCuentaPedidosRouteWithChildren =
  DashboardMiCuentaPedidosRoute._addFileChildren(
    DashboardMiCuentaPedidosRouteChildren,
  )

interface DashboardPedidosIdRouteChildren {
  DashboardPedidosIdClienteRoute: typeof DashboardPedidosIdClienteRoute
  DashboardPedidosIdHistorialRoute: typeof DashboardPedidosIdHistorialRoute
  DashboardPedidosIdPagosRoute: typeof DashboardPedidosIdPagosRoute
  DashboardPedidosIdProductosRoute: typeof DashboardPedidosIdProductosRoute
  DashboardPedidosIdResumenRoute: typeof DashboardPedidosIdResumenRoute
  DashboardPedidosIdIndexRoute: typeof DashboardPedidosIdIndexRoute
}

const DashboardPedidosIdRouteChildren: DashboardPedidosIdRouteChildren = {
  DashboardPedidosIdClienteRoute: DashboardPedidosIdClienteRoute,
  DashboardPedidosIdHistorialRoute: DashboardPedidosIdHistorialRoute,
  DashboardPedidosIdPagosRoute: DashboardPedidosIdPagosRoute,
  DashboardPedidosIdProductosRoute: DashboardPedidosIdProductosRoute,
  DashboardPedidosIdResumenRoute: DashboardPedidosIdResumenRoute,
  DashboardPedidosIdIndexRoute: DashboardPedidosIdIndexRoute,
}

const DashboardPedidosIdRouteWithChildren =
  DashboardPedidosIdRoute._addFileChildren(DashboardPedidosIdRouteChildren)

interface DashboardProductosIdRouteChildren {
  DashboardProductosIdImagenesRoute: typeof DashboardProductosIdImagenesRoute
  DashboardProductosIdInfoRoute: typeof DashboardProductosIdInfoRoute
  DashboardProductosIdInventarioRoute: typeof DashboardProductosIdInventarioRoute
  DashboardProductosIdPreciosRoute: typeof DashboardProductosIdPreciosRoute
  DashboardProductosIdSeoRoute: typeof DashboardProductosIdSeoRoute
  DashboardProductosIdVariantesRoute: typeof DashboardProductosIdVariantesRoute
  DashboardProductosIdIndexRoute: typeof DashboardProductosIdIndexRoute
}

const DashboardProductosIdRouteChildren: DashboardProductosIdRouteChildren = {
  DashboardProductosIdImagenesRoute: DashboardProductosIdImagenesRoute,
  DashboardProductosIdInfoRoute: DashboardProductosIdInfoRoute,
  DashboardProductosIdInventarioRoute: DashboardProductosIdInventarioRoute,
  DashboardProductosIdPreciosRoute: DashboardProductosIdPreciosRoute,
  DashboardProductosIdSeoRoute: DashboardProductosIdSeoRoute,
  DashboardProductosIdVariantesRoute: DashboardProductosIdVariantesRoute,
  DashboardProductosIdIndexRoute: DashboardProductosIdIndexRoute,
}

const DashboardProductosIdRouteWithChildren =
  DashboardProductosIdRoute._addFileChildren(DashboardProductosIdRouteChildren)

interface DashboardRouteChildren {
  DashboardConfiguracionRoute: typeof DashboardConfiguracionRouteWithChildren
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBundlesIdRoute: typeof DashboardBundlesIdRoute
  DashboardBundlesNuevoRoute: typeof DashboardBundlesNuevoRoute
  DashboardCarritosAbandonadosIdRoute: typeof DashboardCarritosAbandonadosIdRoute
  DashboardClientesIdRoute: typeof DashboardClientesIdRoute
  DashboardCuponesIdRoute: typeof DashboardCuponesIdRoute
  DashboardCuponesNuevoRoute: typeof DashboardCuponesNuevoRoute
  DashboardMiCuentaPedidosRoute: typeof DashboardMiCuentaPedidosRouteWithChildren
  DashboardPaginasIdRoute: typeof DashboardPaginasIdRoute
  DashboardPaginasNuevoRoute: typeof DashboardPaginasNuevoRoute
  DashboardPedidosIdRoute: typeof DashboardPedidosIdRouteWithChildren
  DashboardProductosIdRoute: typeof DashboardProductosIdRouteWithChildren
  DashboardProductosNuevoRoute: typeof DashboardProductosNuevoRoute
  DashboardResenasIdRoute: typeof DashboardResenasIdRoute
  DashboardBundlesIndexRoute: typeof DashboardBundlesIndexRoute
  DashboardCarritosAbandonadosIndexRoute: typeof DashboardCarritosAbandonadosIndexRoute
  DashboardCategoriasIndexRoute: typeof DashboardCategoriasIndexRoute
  DashboardClientesIndexRoute: typeof DashboardClientesIndexRoute
  DashboardCuponesIndexRoute: typeof DashboardCuponesIndexRoute
  DashboardInventarioIndexRoute: typeof DashboardInventarioIndexRoute
  DashboardMiCuentaIndexRoute: typeof DashboardMiCuentaIndexRoute
  DashboardPaginasIndexRoute: typeof DashboardPaginasIndexRoute
  DashboardPedidosIndexRoute: typeof DashboardPedidosIndexRoute
  DashboardProductosIndexRoute: typeof DashboardProductosIndexRoute
  DashboardResenasIndexRoute: typeof DashboardResenasIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfiguracionRoute: DashboardConfiguracionRouteWithChildren,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBundlesIdRoute: DashboardBundlesIdRoute,
  DashboardBundlesNuevoRoute: DashboardBundlesNuevoRoute,
  DashboardCarritosAbandonadosIdRoute: DashboardCarritosAbandonadosIdRoute,
  DashboardClientesIdRoute: DashboardClientesIdRoute,
  DashboardCuponesIdRoute: DashboardCuponesIdRoute,
  DashboardCuponesNuevoRoute: DashboardCuponesNuevoRoute,
  DashboardMiCuentaPedidosRoute: DashboardMiCuentaPedidosRouteWithChildren,
  DashboardPaginasIdRoute: DashboardPaginasIdRoute,
  DashboardPaginasNuevoRoute: DashboardPaginasNuevoRoute,
  DashboardPedidosIdRoute: DashboardPedidosIdRouteWithChildren,
  DashboardProductosIdRoute: DashboardProductosIdRouteWithChildren,
  DashboardProductosNuevoRoute: DashboardProductosNuevoRoute,
  DashboardResenasIdRoute: DashboardResenasIdRoute,
  DashboardBundlesIndexRoute: DashboardBundlesIndexRoute,
  DashboardCarritosAbandonadosIndexRoute:
    DashboardCarritosAbandonadosIndexRoute,
  DashboardCategoriasIndexRoute: DashboardCategoriasIndexRoute,
  DashboardClientesIndexRoute: DashboardClientesIndexRoute,
  DashboardCuponesIndexRoute: DashboardCuponesIndexRoute,
  DashboardInventarioIndexRoute: DashboardInventarioIndexRoute,
  DashboardMiCuentaIndexRoute: DashboardMiCuentaIndexRoute,
  DashboardPaginasIndexRoute: DashboardPaginasIndexRoute,
  DashboardPedidosIndexRoute: DashboardPedidosIndexRoute,
  DashboardProductosIndexRoute: DashboardProductosIndexRoute,
  DashboardResenasIndexRoute: DashboardResenasIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadthingSplatRoute: ApiUploadthingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
